"""Generate a synthetic SPY option-chain session for development & demos.

Produces a JSON file in data/recordings/ matching the exact schema that
data.loader.load_session() expects, so the dashboard, surface APIs, and NN
training all work without a live IBKR feed.

The surface is physically plausible: a volatility smile/skew across strikes,
a gently rising term structure, and Black-Scholes greeks consistent with the
implied vols. Spot drifts slightly across frames to give the models something
to learn.

Run:  python data/make_sample_session.py
"""

import json
import math
from datetime import date, timedelta
from pathlib import Path

import numpy as np
from scipy.stats import norm

RECORDINGS = Path(__file__).parent / "recordings"


def _bs_greeks(S, K, T, sigma, r=0.045, q=0.0):
    """Black-Scholes call greeks for a single point."""
    if T <= 0 or sigma <= 0:
        return dict(delta=float(S > K), gamma=0.0, vega=0.0, theta=0.0)
    d1 = (math.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * math.sqrt(T))
    d2 = d1 - sigma * math.sqrt(T)
    delta = math.exp(-q * T) * norm.cdf(d1)
    gamma = math.exp(-q * T) * norm.pdf(d1) / (S * sigma * math.sqrt(T))
    vega = S * math.exp(-q * T) * norm.pdf(d1) * math.sqrt(T) / 100.0
    theta = (-(S * math.exp(-q * T) * norm.pdf(d1) * sigma) / (2 * math.sqrt(T))
             - r * K * math.exp(-r * T) * norm.cdf(d2)
             + q * S * math.exp(-q * T) * norm.cdf(d1)) / 365.0
    return dict(delta=delta, gamma=gamma, vega=vega, theta=theta)


def _smile_iv(S, K, T):
    """Synthetic IV with put-skew and a mild term-structure rise."""
    m = math.log(K / S)                 # log-moneyness
    base = 0.16 + 0.04 * math.sqrt(T)   # term structure
    skew = -0.55 * m                    # OTM puts richer than OTM calls
    curve = 2.2 * m * m                 # convex smile
    return float(np.clip(base + skew + curve, 0.05, 1.2))


def build_session(symbol="SPY", spot0=530.0, n_strikes=21, strike_step=5.0,
                  expiry_days=(7, 14, 30, 60, 90), n_frames=12, seed=7):
    rng = np.random.default_rng(seed)
    today = date(2026, 6, 7)

    center = round(spot0 / strike_step) * strike_step
    half = n_strikes // 2
    strikes = [float(center + (i - half) * strike_step) for i in range(n_strikes)]

    expiries = [{
        "date": (today + timedelta(days=d)).isoformat(),
        "days": int(d),
        "T": round(d / 365.0, 6),
    } for d in expiry_days]

    NE, NS = len(expiries), len(strikes)
    snapshots = []

    # Spot follows a small random walk over the session.
    spot = spot0
    for fi in range(n_frames):
        spot += float(rng.normal(0, 0.6))
        iv_flat, delta_flat, gamma_flat, vega_flat, theta_flat = [], [], [], [], []
        coi_flat, poi_flat, cvol_flat, pvol_flat = [], [], [], []

        for e in expiries:
            T = e["T"]
            for K in strikes:
                iv = _smile_iv(spot, K, T) + float(rng.normal(0, 0.003))
                iv = max(iv, 0.03)
                g = _bs_greeks(spot, K, T, iv)
                iv_flat.append(round(iv, 5))
                delta_flat.append(round(g["delta"], 5))
                gamma_flat.append(round(g["gamma"], 6))
                vega_flat.append(round(g["vega"], 5))
                theta_flat.append(round(g["theta"], 6))

                # Open interest / volume: peak near the money.
                atm = math.exp(-((K - spot) / (strike_step * 6)) ** 2)
                coi_flat.append(int(2000 * atm + rng.integers(0, 400)))
                poi_flat.append(int(2400 * atm + rng.integers(0, 400)))
                cvol_flat.append(int(500 * atm + rng.integers(0, 150)))
                pvol_flat.append(int(600 * atm + rng.integers(0, 150)))

        snapshots.append({
            "t": f"2026-06-07T{13 + fi // 4:02d}:{(fi * 15) % 60:02d}:00Z",
            "underlying": round(spot, 2),
            "iv": iv_flat,
            "callDelta": delta_flat,
            "gamma": gamma_flat,
            "vega": vega_flat,
            "callTheta": theta_flat,
            "callOI": coi_flat,
            "putOI": poi_flat,
            "callVol": cvol_flat,
            "putVol": pvol_flat,
        })

    return {
        "meta": {
            "symbol": symbol,
            "sessionDate": today.isoformat(),
            "source": "synthetic",
            "note": "Generated by data/make_sample_session.py for dev/demo.",
            "spot0": spot0,
        },
        "strikes": strikes,
        "expiries": expiries,
        "snapshots": snapshots,
    }


def main():
    RECORDINGS.mkdir(parents=True, exist_ok=True)
    session = build_session()
    out = RECORDINGS / f"session-{session['meta']['sessionDate']}.json"
    out.write_text(json.dumps(session))
    nf = len(session["snapshots"])
    ne = len(session["expiries"])
    ns = len(session["strikes"])
    print(f"Wrote {out}  ({nf} frames x {ne} expiries x {ns} strikes)")


if __name__ == "__main__":
    main()
